### ISSUE TITLE
Bug: crashes when emptying EditTexts

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [firebase/firebase-jobdispatcher-android#14]
Sample doesn't allow to clear the text of the EditText.
I wanted to know what each EditText is for, so I thought clearing it will show the hint, but it crashes.

Here's the log:

06-09 11:16:31.963 23986-23986/com.firebase.jobdispatcher.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.firebase.jobdispatcher.testapp, PID: 23986
                                                                                    java.lang.NumberFormatException: Invalid int: ""
                                                                                        at java.lang.Integer.invalidInt(Integer.java:138)
                                                                                        at java.lang.Integer.parseInt(Integer.java:358)
                                                                                        at java.lang.Integer.valueOf(Integer.java:545)
                                                                                        at com.firebase.jobdispatcher.testapp.JobForm.setWinStartSecondsStr(JobForm.java:43)
                                                                                        at com.firebase.jobdispatcher.testapp.databinding.ActivityJobFormBinding$3.onChange(ActivityJobFormBinding.java:109)
                                                                                        at android.databinding.adapters.TextViewBindingAdapter$1.onTextChanged(TextViewBindingAdapter.java:367)
                                                                                        at android.widget.TextView.sendOnTextChanged(TextView.java:7988)
                                                                                        at android.widget.TextView.handleTextChanged(TextView.java:8050)
                                                                                        at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10154)
                                                                                        at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1033)
                                                                                        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:559)
                                                                                        at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:225)
                                                                                        at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:224)
                                                                                        at android.view.inputmethod.BaseInputConnection.deleteSurroundingText(BaseInputConnection.java:244)
                                                                                        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:389)
                                                                                        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by AndroidDeveloperLB** [comment]
I suggest using  this:

    <android.support.design.widget.TextInputLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

        <android.support.design.widget.TextInputEditText android:hint="..." />

    </android.support.design.widget.TextInputLayout>

**Comment by ciarand** [comment]
Thanks for the report! This should be fixed now. The sample app is a little barebones at the moment, but that's no excuse for it crashing.

**Comment by HenningBu** [comment]
Still crashes when deleting the values of the backoff strategy.
