### ISSUE TITLE
Issue while scheduling Firebase JobDispatcher job - Too many tasks scheduled for this package. Not scheduling

### ISSUE THREAD

**Issue by abhinavbr** [firebase/firebase-jobdispatcher-android#155]
We are using firebase-jobdispatcher version 0.6.0 for scheduling our jobs. When we try to schedule new jobs we get -
`NetworkScheduler: Too many tasks scheduled for this package. Not scheduling: [package.name/com.firebase.jobdispatcher.GooglePlayReceiver:taskFailed,u0]`

More information - We are scheduling 6 jobs and using setreplacecurrent(true) on all of them.

Edit 1: This issue persists even when I reinstall the app but goes away when I change package name of the app. Also, when I check number of task count by user and package name using "adb shell dumpsys activity service GcmService --endpoints", it shows 110. The number of task for my app's package remain same after uninstalling the app and calling cancelAll with FirebaseJobDispatcher.

**Comment by unEgor** [comment]
Hi
Thank you for reporting the bug. The fix will be release with new version 0.8.2 of firebase-jobdispatcher-android.

**Comment by abhinavbr** [comment]
@unEgor Thanks for the quick response. Is there a temporary fix that I can use in the meantime?

**Comment by tgb2006** [comment]
I am facing Same Issue. Is there any workaround?

**Comment by unEgor** [comment]
Fixed in https://github.com/firebase/firebase-jobdispatcher-android/releases/tag/v0.8.2

**Comment by tschuchortdev** [comment]
I'm depending on version 0.8.2 and still getting this error. Do you somehow have to cancel all the existing jobs before updating for the fix to take effect?

**Comment by abhinavbr** [comment]
@tschuchortdev The only solution I have found so far is to restart the phone. Restarting the phone clears all the tasks.

**Comment by tschuchortdev** [comment]
restarting the device after upgrading to 0.8.2 seems to fix the error for now.

**Comment by unEgor** [comment]
Unfortunately I'm not able to reproduce it on 0.8.2
Could you please provide exact steps and version of Google Play Services?
And the bugreport if it is possible.

**Comment by tschuchortdev** [comment]
Google Play Services version: 11.6.73 

To reproduce, use version 0.8.1 to trigger the bug, then upgrade to 0.8.2 and scheduling tasks should still fail with the same error until all tasks are cleared by restarting the device. 

Not something worth investigating probably, since it only seems to occur in this specific scenario.
